{% set name = "ultimate-sitemap-parser" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ultimate_sitemap_parser-{{ version }}.tar.gz
  sha256: c227dd10da5c5d6ec67c4add04170d0ee4008d966bf8c489a002bf3e85b35983

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0.1
    - pytest-runner >=4.2,<5.0
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.7,<3.0.0
    - requests >=2.2.1,<3.0.0

test:
  imports:
    - usp
  commands:
    - pip check
    - usp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ultimate-sitemap-parser.readthedocs.io
  dev_url: https://github.com/GateNLP/ultimate-sitemap-parser
  doc_url: https://ultimate-sitemap-parser.readthedocs.io
  summary: A performant library for parsing and crawling sitemaps
  license: GPL-3.0-or-later
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - freddyheppell
