{% set name = "ultimate-sitemap-parser" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ultimate_sitemap_parser-{{ version }}.tar.gz
  sha256: 0d2577e33d513fd4b5890d013eb42ca4a26f20871c85928f854ffda47063a40c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner >=4.2,<5.0
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.1,<3.0.0
    - requests >=2.2.1

test:
  imports:
    - usp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser
  summary: Ultimate Sitemap Parser
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - freddyheppell
